// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Keep the autogenerated tutorial sidebar
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  
  // Updated book sidebar with all 37 chapters
  bookSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: '🤖 Module 1: ROS 2 Fundamentals',
      collapsed: false,
      items: [
        'module1/chapter01',
        'module1/chapter02',
        'module1/chapter03',
        'module1/chapter04',
        'module1/chapter05',
        'module1/chapter06',
        'module1/chapter07',
        'module1/chapter08',
        'module1/chapter09',
        'module1/chapter10',
      ],
    },
    {
      type: 'category',
      label: '🎮 Module 2: Gazebo/Unity Simulation',
      collapsed: true,
      items: [
        'module2/chapter11',
        'module2/chapter12',
        'module2/chapter13',
        'module2/chapter14',
        'module2/chapter15',
        'module2/chapter16',
        'module2/chapter17',
        'module2/chapter18',
      ],
    },
    {
      type: 'category',
      label: '⚡ Module 3: NVIDIA Isaac',
      collapsed: true,
      items: [
        'module3/chapter19',
        'module3/chapter20',
        'module3/chapter21',
        'module3/chapter22',
        'module3/chapter23',
        'module3/chapter24',
        'module3/chapter25',
        'module3/chapter26',
        'module3/chapter27',
        'module3/chapter28',
      ],
    },
    {
      type: 'category',
      label: '🧠 Module 4: Vision-Language-Action Models',
      collapsed: true,
      items: [
        'module4/chapter29',
        'module4/chapter30',
        'module4/chapter31',
        'module4/chapter32',
        'module4/chapter33',
        'module4/chapter34',
        'module4/chapter35',
        'module4/chapter36',
        'module4/chapter37',
      ],
    },
  ],
};

module.exports = sidebars;