/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics",
  "tagline": "An interactive AI-powered learning platform featuring 43 chapters across 4 modules covering ROS 2, Gazebo/Unity simulation, NVIDIA Isaac, and Vision-Language-Action models for humanoid robotics",
  "favicon": "img/favicon.ico",
  "url": "https://your-site.netlify.app",
  "baseUrl": "/",
  "organizationName": "azmataliakbar",
  "projectName": "ai-robotics-book",
  "onBrokenLinks": "ignore",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "routeBasePath": "docs"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "blogTitle": "Physical AI Blog",
          "blogDescription": "Updates and insights on Physical AI and Humanoid Robotics",
          "postsPerPage": "ALL",
          "blogSidebarTitle": "All posts",
          "blogSidebarCount": "ALL"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "🤖 Physical AI & Humanoid Robotics",
      "logo": {
        "alt": "Robotics Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/",
          "label": "Home",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "sidebarId": "bookSidebar",
          "position": "left",
          "label": "📚 Book"
        },
        {
          "to": "/blog",
          "label": "📝 Blog",
          "position": "left"
        },
        {
          "to": "/chat",
          "label": "💬 AI Chat",
          "position": "left"
        },
        {
          "href": "https://github.com/azmataliakbar",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "📚 Book Modules",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/intro"
            },
            {
              "label": "Module 1: ROS 2",
              "to": "/docs/intro"
            },
            {
              "label": "Module 2: Gazebo/Unity",
              "to": "/docs/intro"
            },
            {
              "label": "Module 3: NVIDIA Isaac",
              "to": "/docs/intro"
            },
            {
              "label": "Module 4: VLA Models",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "🌐 Community",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "ROS 2 Docs",
              "href": "https://docs.ros.org/"
            },
            {
              "label": "ROS Discourse",
              "href": "https://discourse.ros.org/"
            },
            {
              "label": "NVIDIA Isaac",
              "href": "https://developer.nvidia.com/isaac-sdk"
            }
          ]
        },
        {
          "title": "👨‍💻 Author",
          "items": [
            {
              "label": "Azmat Ali",
              "href": "mailto:azmataliakbar@gmail.com"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/azmataliakbar"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/azmataliakbar"
            }
          ]
        },
        {
          "title": "🚀 Features",
          "items": [
            {
              "label": "AI Chat Assistant",
              "to": "/chat"
            },
            {
              "label": "Search",
              "to": "/search"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Physical AI & Humanoid Robotics. Built with Docusaurus & FastAPI."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "bash",
        "yaml",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "ignore",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
